### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by emtiazzahid** [Lisennk/Slack-Events#11]
Trying to install in Laravel 6.8
Exception:

```
Installation request for lisennk/laravel-slack-events-api ^1.1 -> satisfiable by lisennk/laravel-slack-events-api[1.1].
    - Conclusion: remove laravel/framework v6.11.0
    - Conclusion: don't install laravel/framework v6.11.0
    - lisennk/laravel-slack-events-api 1.1 requires illuminate/routing 5.1.*|5.2.*|5.3.*|5.4.* -> satisfiable by illuminate/routing[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].

```

**Comment by jhavenz** [comment]
Same here...using Laravel 7.19.

Plan to fix? Looks like this has been an issue for quite a while now.

**Comment by pelmered** [comment]
Master is working fine with both Laravel 6 and 7. What is needed is just a new release. Until then we have to use `dev-master`.

**Comment by Lisennk** [comment]
@pelmered could you please make a PR? Or I can transfer repository so you could control it. I can't do that anymore since I am no longer a user of Laravel or PHP.

**Comment by pelmered** [comment]
@Lisennk Ok, but I don't think a PR would be necessary. 
I haven't done any testing outside my use cases, but I think what is in the master branch right now is ok for tagging a new release. I have been using this without any problems in production for some time now. 

If you don't want to maintain this anymore I could take over the project if you want. You can either add me as a contributor with full access here or transfer the project to my profile. That is up to you.

**Comment by Lisennk** [comment]
@pelmered I've sent you an invite

**Comment by pelmered** [comment]
@Lisennk Thanks a lot! I tagged a new release now. The tests are not working, but I think it's pretty safe to release anyway. It's not a huge install base. I will see if I can fix the tests later.

Can you fix auto-updates on https://packagist.org/ ?
Instructions are at the bottom of this page: https://packagist.org/about
Now I updated the package manually.
